# conda env create -f environment.yml
name: file_download_stat
channels:
  - conda-forge
  - bioconda
dependencies:
  - openjdk=17.0.13   # Compatible Java version for Nextflow
  - python=3.10
  - pip
  - pip:
      - nextflow>=22.10.6
      - pyreadr>=0.4.6
      - pandas>=1.5.3
      - glob2>=0.7
      - numpy>=1.23.5
      - pyarrow>=10.0.1
      - dask>=2023.1.0
      - plotly
      - mkdocs